/// Generated by AssetsRefGenerator on 2020/05/03
class Res {
  static const String demo_logo = "images/demo_logo.png";
  static const String icon_connect = "images/icon_connect.png";
  static const String icon_found = "images/icon_found.png";
  static const String icon_mine = "images/icon_mine.png";
  static const String icon_wechat = "images/icon_wechat.png";
  static const String splash_bg = "images/splash_bg.png";
}
