/// Generated by AssetsRefGenerator on 2020/05/04
class Res {
  static const String demo_logo = "images/demo_logo.png";
  static const String icon_connect = "images/icon_connect.png";
  static const String icon_connect_selected = "images/icon_connect_selected.png";
  static const String icon_found = "images/icon_found.png";
  static const String icon_found_selected = "images/icon_found_selected.png";
  static const String icon_mine = "images/icon_mine.png";
  static const String icon_mine_selected = "images/icon_mine_selected.png";
  static const String icon_wechat = "images/icon_wechat.png";
  static const String icon_wechat_selected = "images/icon_wechat_selected.png";
  static const String iconfont = "images/iconfont.ttf";
  static const String splash_bg = "images/splash_bg.png";
}
